### ISSUE TITLE
Native hook

### ISSUE THREAD

**Issue by obbana2** [Rprop/AndHook#36]
Good afternoon. I started using your library and am very pleased with the results and convenience. Almost immediately I ran into a problem.

I intercept AudioRecord in another application when there is an AudioRecord call from java - everything is fine, when the call comes from the native library, nothing works. Interception simply does not happen, although this function is api in Java, after all? It simply can not be carried out natively. How can you deal with this? I can not decompile the native library, but there are clearly calls to <init>, startRecording and read of the AudioRecord class.

**Comment by henrytom1703** [comment]
Hello @obbana2 
Can you guide me how to  intercept AudioRecord in another application?
Thanks

**Comment by obbana2** [comment]
[ObbanaHook.zip](https://github.com/Rprop/AndHook/files/1985088/ObbanaHook.zip)
Here is my project. The application actually reads the data from the microphone into the blank, but they remain in the files. Connection hook occurs in the ContentProvider, the dex file can be placed in another's application called classes2.dex, after removing the extra builds of the type java compat. You also need to register the ContentProvider in the AndroidManifest of another application. Thus, you can debug and patch applications without making changes to the original classes.dex code and resources

**Comment by Rprop** [comment]
either java or ndk is ok:
```
@Hook(clazz = AudioRecord.class)
private static int native_start(final Object objAudioRecord, int syncEvent, int sessionId) {
}
```

**Comment by obbana2** [comment]
I partially prijuizilis to the truth. The application reproduces and records audio also via OpenSL ES. In C / C ++, I'm just a beginner, so I do not even know how to intercept this.

**Comment by Rprop** [comment]
you probably need to intercept `OpenSLEngineInterface->CreateAudioRecorder` in native code, just follow Google's guides at https://developer.android.com/ndk/guides/audio/opensl-prog-notes.html

**Comment by obbana2** [comment]
Thanks, I'll try to figure it out. Can I contact you for more questions outside of github?

**Comment by Rprop** [comment]
Yes, you can contact me by email.
