### ISSUE TITLE
在x86模拟器houdini arm环境的arm so的app上

### ISSUE THREAD

**Issue by fuck-u-s** [Rprop/AndHook#38]
TEST123 : JNI->java_hook
05-11 12:49:12.790  5009  5009 V java_hook: starting jni hook...
05-11 12:49:12.791  5009  5009 W AndHook : unable to suspend all java threads, no guarantee of thread safety!
05-11 12:49:12.791  5009  5009 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 5009 (com.tencent.mm)
05-11 12:49:12.892  1646  1646 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-11 12:49:12.892  1646  1646 F DEBUG   : Build fingerprint: 'x86_64_arm/x86_64_arm/x86_64_arm:6.0.1/MOB31T/hnidc04181050:userdebug/test-keys'
05-11 12:49:12.892  1646  1646 F DEBUG   : Revision: '0'
05-11 12:49:12.892  1646  1646 F DEBUG   : ABI: 'x86'
05-11 12:49:12.892  1646  1646 F DEBUG   : pid: 5009, tid: 5009, name: com.tencent.mm  >>> com.tencent.mm <<<
05-11 12:49:12.893  1646  1646 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
05-11 12:49:12.915  1646  1646 F DEBUG   :     eax ef2a6adc  ebx ed6d0ed8  ecx 00000043  edx 00000000
05-11 12:49:12.916  1646  1646 F DEBUG   :     esi 00000000  edi ef2a6ac8
05-11 12:49:12.916  1646  1646 F DEBUG   :     xcs 00000023  xds 0000002b  xes 0000002b  xfs 00000007  xss 0000002b
05-11 12:49:12.916  1646  1646 F DEBUG   :     eip 00000000  ebp ed6e3d60  esp fff8677c  flags 00210296
05-11 12:49:12.917  1646  1646 F DEBUG   :
05-11 12:49:12.917  1646  1646 F DEBUG   : backtrace:
05-11 12:49:12.917  1646  1646 F DEBUG   :     #00 pc 00000000  <unknown>
05-11 12:49:12.917  1646  1646 F DEBUG   :     #01 pc 00093f7f  /data/dalvik-cache/x86/system@framework@boot.art

**Comment by Rprop** [comment]
如果需要运行在x86平台, java层的hook的请在java层进行, 最终由AKCompact完成.
如果需要在x86上去拦截arm native函数, 则需要编译arm版本的so, 建议使用其它框架完成.

**Comment by fuck-u-s** [comment]
ok
