### ISSUE TITLE
请问如何方便联系您

### ISSUE THREAD

**Issue by newtalentxp** [Rprop/AndHook#43]
请问如何方便联系您。出现很多版本兼容性问题。。可否留个常用邮箱或者微信, 微博？

**Comment by Rprop** [comment]
我暂时没有时间处理这些问题, 建议选择其它框架

**Comment by Rprop** [comment]
大概是什么问题, 可以发邮件我, 在资料里有, 最近好多事, 有时间的话会尽量解决, 谢谢

**Comment by newtalentxp** [comment]
系统上的确安装了xposed的，那要自己去设置 java.io.tmpdir?

**Comment by newtalentxp** [comment]
/system/bin/dex2oat --dex-file=/sdcard/dms/wechat-hook-debug.zip --oat-file=/data/user/0/io.virtualapp/virtual/opt/my-hook.dex
05-22 01:50:36.042 32760 32760 E dex2oat : Could not create image space with image file '/system/framework/boot.art'. Attempting to fall back to imageless running. Error was: Only the zygote can create the global boot image.

**Comment by newtalentxp** [comment]
/system/bin/dex2oat --dex-file=/sdcard/my-hook.zip --oat-file=/data/user/0/io.virtualapp/virtual/opt/my-hook.dex
05-22 01:50:36.042 32760 32760 E dex2oat : Could not create image space with image file '/system/framework/boot.art'. Attempting to fall back to imageless running. Error was: Only the zygote can create the global boot image.

**Comment by Rprop** [comment]
有无安装xposed原则上不影响框架运行，但是如果你要在xp模块的入口点进行加载就需要设置，后面有时间会解决了这个问题
