### ISSUE TITLE
unexpected houdini environment

### ISSUE THREAD

**Issue by obbana2** [Rprop/AndHook#47]
Hello, I've seen this error, instead of notifying you of the successful use of hooks. I'm testing the program on the Nox emulator (Android x86) on Windows 10 x64. I can not understand if the emulator or x64 platform is to blame

**Comment by obbana2** [comment]
unexpected houdini environment

**Comment by Rprop** [comment]
In order to let your app (with JNI hooks) run in the x86 emulator, you must have x86 so included.
