### ISSUE TITLE
[Help] cannot hook stat

### ISSUE THREAD

**Issue by nakcont** [Rprop/AndHook#48]
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *)
{
    struct stat buf;
    char *res="/system/xbin/su";
    int resultNow = stat(res, &buf) == 0 ? 1 : 0;
    if (resultNow == 1) {
        AKLog("IS ROOTED");
    } else
    {
        AKLog("NOT ROTED");
    }
    return JNI_VERSION_1_6;
}

i cannot hook "stat" . Please help me. i try AKHook(stat) but not working

**Comment by Rprop** [comment]
Since `stat` is a kind of ambiguous symbol, you probably have to make it clear (e.g. get its function pointer first and then use `AKHookFunction` directly).

**Comment by nakcont** [comment]
Can you give me the example above?

**Comment by nakcont** [comment]
I did check again, Source build with NDK =>  `AKHook(stat)` working fine , but source build with Cmake, `AKHook(stat)` not working ? pls help me :(

**Comment by Rprop** [comment]
Please attach the CMake error message.

**Comment by nakcont** [comment]
Sorry, my Cmake not error message, I want to ask you how hook function stat :(
i cannot hook it with AKHook(stat), please give me the any examples. thanks you

`struct stat buf;
char *res="/system/xbin/su";
int resultNow = stat(res, &buf) == 0 ? 1 : 0;
if (resultNow == 1) {
AKLog("IS ROOTED");
} else
{
AKLog("NOT ROTED");
}`

**Comment by nakcont** [comment]
My AKHook(stat)


`int(*sys_stat)(const char *name, struct stat *value);
int my_stat(const char *name, struct stat *value) {
    
    if (strstr(name, "/system/xbin/su") != NULL)
    {
        return -1;
    }
    return sys_stat(name, value);

}`

**Comment by Rprop** [comment]
Are you sure `AKHook(stat)` is called properly before `stat`?

**Comment by nakcont** [comment]
Yes, i sure AKHook(stat) call before run stat;

**Comment by Rprop** [comment]
That's impossible, inline hook should never fail without crashing the application.

**Comment by nakcont** [comment]
OK, thanks you, i think my mistake. i will build again .
