### ISSUE TITLE
Needs more documentation

### ISSUE THREAD

**Issue by d3vvil** [Rprop/AndHook#52]
Some of the functions are very vague, like `AKWrapFunction`. Documenting the return values or use-cases for each of the functions would help a ton!

**Comment by Rprop** [comment]
Sorry for the inconvenience.
According to the ARM/ARM64 calling convention, the rules about which registers need to be preserved and which can be modified across procedure calls are well-defined. 
However, for internal functions, the compiler may make the assumption that the temporary registers ( not require preserving ) will not change value, and as a result, if we intercept such functions, we will have to save those registers ourselves and restore them before return, that's what `AKWrapFunction` does.
